// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqwaasdjpxlucgsknryp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxd2Fhc2RqcHhsdWNnc2tucnlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTQ0NDksImV4cCI6MjA3MzI3MDQ0OX0.7edknT33F4_EOQXU3-PlbBqmt6G1TDXaDA8EkiUas6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});